-- 코드를 입력하세요
SELECT A.AUTHOR_ID,
       B.AUTHOR_NAME,
       A.CATEGORY,
       A.TOTAL_SALES
FROM (SELECT BB.AUTHOR_ID,
             AA.CATEGORY,
             SUM(CC.SALES*AA.PRICE) AS TOTAL_SALES
      FROM BOOK AA, AUTHOR BB, BOOK_SALES CC
      WHERE AA.BOOK_ID=CC.BOOK_ID AND AA.AUTHOR_ID=BB.AUTHOR_ID
      AND TO_CHAR(CC.SALES_DATE,'YYYY-MM')='2022-01'
      GROUP BY BB.AUTHOR_ID, AA.CATEGORY) A, AUTHOR B
WHERE A.AUTHOR_ID=B.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC