SELECT ANIMAL_ID, NAME
FROM (
SELECT B.DATETIME - A.DATETIME AS DATEDIFF, A.ANIMAL_ID, A.NAME
  FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON B.ANIMAL_ID = A.ANIMAL_ID
 ORDER BY DATEDIFF DESC)
 WHERE ROWNUM <=2
 