-- 코드를 입력하세요
SELECT B.PRODUCT_ID,
       A.PRODUCT_NAME,
       B.TOTAL_SALES
FROM (SELECT P.PRODUCT_ID,
      SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
      FROM FOOD_PRODUCT P, FOOD_ORDER O
      WHERE P.PRODUCT_ID=O.PRODUCT_ID
      AND TO_CHAR(O.PRODUCE_DATE,'YYYY-MM')='2022-05'
      GROUP BY P.PRODUCT_ID) B, FOOD_PRODUCT A
WHERE A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY B.TOTAL_SALES DESC, A.PRODUCT_ID