-- 코드를 입력하세요
SELECT C.FLAVOR
FROM (SELECT A.FLAVOR,
             SUM(A.TOTAL_ORDER)+SUM(B.TOTAL_ORDER) AS TOTAL_ORDER
     FROM FIRST_HALF A INNER JOIN JULY B
     ON A.FLAVOR = B.FLAVOR
     GROUP BY A.FLAVOR
     ORDER BY TOTAL_ORDER DESC) C
WHERE ROWNUM<=3; 