-- 코드를 입력하세요
WITH C AS (SELECT MEMBER_ID, COUNT(*) AS COUNT
               FROM REST_REVIEW
               GROUP BY MEMBER_ID
               ORDER BY COUNT DESC 
           FETCH FIRST ROW ONLY)
SELECT A.MEMBER_NAME, 
       B.REVIEW_TEXT, 
       TO_CHAR(B.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
AND B.MEMBER_ID = (SELECT C.MEMBER_ID
                    FROM C)
ORDER BY REVIEW_DATE, REVIEW_TEXT