SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH
    FROM FISH_INFO
    WHERE (FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH) 
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )
) AS A
LEFT OUTER JOIN FISH_NAME_INFO AS B ON B.FISH_TYPE = A.FISH_TYPE
ORDER BY A.ID;