-- 코드를 입력하세요
SELECT '/home/grep/src/'||B.BOARD_ID||'/'||FILE_ID||FILE_NAME||FILE_EXT AS FILE_PATH
FROM(SELECT * FROM(
SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC)
    WHERE ROWNUM = 1) A
LEFT OUTER JOIN USED_GOODS_FILE B ON B.BOARD_ID = A.BOARD_ID
ORDER BY FILE_ID DESC