SELECT CATEGORY, TOTSALES AS TOTAL_SALES
FROM (
SELECT A.CATEGORY, SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMMDD'), 1, 6) AS SALESDATE, SUM(SALES) AS TOTSALES
FROM BOOK A JOIN BOOK_SALES B ON B.BOOK_ID = A.BOOK_ID
GROUP BY CATEGORY, SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMMDD'), 1, 6))
WHERE SALESDATE = '202201'
ORDER BY CATEGORY