-- 코드를 입력하세요
SELECT B.CATEGORY,
       A.MAX_PRICE,
       B.PRODUCT_NAME
FROM (SELECT CATEGORY,
             MAX(PRICE) AS MAX_PRICE
     FROM FOOD_PRODUCT
     GROUP BY CATEGORY
     HAVING CATEGORY IN('식용유','과자','국','김치')) A, FOOD_PRODUCT B
WHERE A.MAX_PRICE=B.PRICE AND A.CATEGORY=B.CATEGORY
ORDER BY MAX_PRICE DESC